version: "3.7"
services:
  shoppinglist-app:
    image: mattcrutchley/shoppinglist-app
    build: .
    ports:
      - target: 5000
        published: 5000
    depends_on:
      - shoppinglist-db
    environment:
      - DATABASE_URI=mysql+pymysql://root:${rootpass}@shoppinglist-db/db
      - SECRET_KEY=${SECRET_KEY}
  shoppinglist-db:
    image: mattcrutchley/shoppinglist-db
    build: ./createsqlimage/
    container_name: shoppinglist-db
    ports:
      - target: 3306
        published: 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${rootpass}
    volumes:
      - type: volume
        source: flasksql
        target: /var/lib/mysql       
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - target: 80
        published: 80
    depends_on:
      - shoppinglist-app
    volumes:
      - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
        
volumes:
  flasksql:
